"""Guardrails for content that must never creep back into the tree.

Names in sample data, fixtures and tools: the client is a Pakistani company,
so sample data uses Middle Eastern and Western names, never Indian ones.
This test greps the source tree (not binary PDFs/PNGs, which are
regenerated by hand and checked visually) for the specific names that used
to be there.

Also guards the report PDFs' "correct" colour, which must never be green -
see the answer-state palette in ``backend/pdf_theme.py``.
"""

import os

from backend import pdf_theme as theme

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Specific strings that were removed from the codebase. Not a general
# ethnicity/surname denylist - just a regression guard for the names this
# project used to ship with.
BANNED_NAME_STRINGS = [
    "Aarav Sharma",
    "Aarav",
    "Sharma",
    "Priya Venkataraman-Subramaniam",
    "Venkataraman",
    "Subramaniam",
    "Demo Student 1",
    "Demo Student 2",
    "Chen Wei",
]

# Only source files - binary PDFs/PNGs are handled by the preview/regen
# workflow (tools/preview_reports.py, tools/preview_exam.py) and looked at
# by eye, not text-scanned.
SCAN_EXTENSIONS = (".py", ".md", ".txt", ".html", ".js")
SKIP_DIRS = {
    ".git", ".venv", "venv", "node_modules", "output", "dist", "build",
    ".pytest-tmp", ".pytest-tmp2", ".ruff_cache", "__pycache__",
}


_SELF_PATH = os.path.abspath(__file__)


def _source_files():
    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".pytest-tmp")]
        for fname in filenames:
            path = os.path.join(dirpath, fname)
            if fname.endswith(SCAN_EXTENSIONS) and os.path.abspath(path) != _SELF_PATH:
                yield path


def test_no_banned_names_in_source_tree():
    hits = []
    for path in _source_files():
        try:
            with open(path, encoding="utf-8") as f:
                text = f.read()
        except (UnicodeDecodeError, OSError):
            continue
        for banned in BANNED_NAME_STRINGS:
            if banned in text:
                hits.append((os.path.relpath(path, REPO_ROOT), banned))
    assert not hits, f"Banned name strings found: {hits}"


def _is_greenish(hex_color):
    """True if green is the clearly dominant channel - the definition of
    "looks green" we care about here, not exact hue matching."""
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return g > r + 15 and g > b + 15


def test_correct_colour_is_never_green():
    correct_hexes = [
        f"#{int(theme.CORRECT.red * 255):02x}"
        f"{int(theme.CORRECT.green * 255):02x}"
        f"{int(theme.CORRECT.blue * 255):02x}",
        theme.CHART_CORRECT,
    ]
    for hex_color in correct_hexes:
        assert not _is_greenish(hex_color), f"{hex_color} reads as green"
